name: test
on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: semeru
          java-version: 11
          java-package: jdk

      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Gradle Test
        run: ./gradlew test

      - name: Publish Results
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/**/*.xml
